### ISSUE TITLE
Image Preprocessing for ImageNet Validation

### ISSUE THREAD

**Issue by gshartnett** [facebookresearch/ImageNet-Adversarial-Training#12]
First of all, thank you very much for your very useful code!

I am attempting to reproduce the quoted numbers in the [Instructions.md](https://github.com/facebookresearch/ImageNet-Adversarial-Training/blob/master/INSTRUCTIONS.md) file, and am having trouble. I suspect the issue may be that I am preprocessing the image differently than the code used to create these results. I was wondering if someone could let me know precisely how the preprocessing must be done in order to reproduce the results (even for "clean" images, i.e. without any adversarial attack).

**Comment by cihangxie** [comment]
you may refer to the answer here: https://github.com/facebookresearch/ImageNet-Adversarial-Training/issues/11
