### ISSUE TITLE
resnet_model.py --> non_local_op

### ISSUE THREAD

**Issue by say2sarwar** [facebookresearch/ImageNet-Adversarial-Training#15]
![Screenshot from 2019-11-04 10-59-19](https://user-images.githubusercontent.com/34134990/68097669-5484ad00-fef3-11e9-9a32-d9dd8c2150c2.png)

if embed:
why did you divide n_in by 2 as n_in / 2. both in theta and phi. i am curious beoz it produce different shape of tensor. Can you please check. the image shows the respective portion.

**Comment by ppwwyyxx** [comment]
Please refer to the paper "nonlocal neural networks".

**Comment by say2sarwar** [comment]
Thank you so much.

**Comment by say2sarwar** [comment]
hello,
i am trying to implement your code in Pytorch. why you choose tensorflow over pytorch? any technical reasons? i am just curious, since that's FAIR work. 
Thanks in advance.
