### ISSUE TITLE
How can I transform the code of de-noising module into Caffe code

### ISSUE THREAD

**Issue by LiuZhe6** [facebookresearch/ImageNet-Adversarial-Training#16]
If you met an unexpected problem when using the code, please include the following in your issues:

1. What you did: try to convert the code of de-noising module to Caffe code

2. What you observed: I can not implement the algorithm of your module using Caffe.

3. What you expected, if not obvious.

Hello.

I want to use this module on a Caffe project. But I have no way to implement the algorithm. For example, this de-noising module used a lot of 'tf.einsum()'. I am new to Caffe. Could you provide some suggestions for me to implement this module using Caffe code?

Thank you !

**Comment by ppwwyyxx** [comment]
The code is released so that readers of the paper can understand and verify our research. What you're asking is beyond the support we would give.

My general suggestion is to not use caffe.
