### ISSUE TITLE
Question about the code for converting variables to FP16

### ISSUE THREAD

**Issue by JunweiLiang** [facebookresearch/ImageNet-Adversarial-Training#18]
Hi, 
I have a question about the code for converting variables to FP16 in [adv_model.py](https://github.com/facebookresearch/ImageNet-Adversarial-Training/blob/master/adv_model.py#L92):

```
if kwargs['dtype'] == tf.float16:
   kwargs['dtype'] = tf.float32
   ret = getter(*args, **kwargs)
   ret = tf.cast(ret, tf.float16)
   log_once("Variable {} casted to fp16 ...".format(name))
   return ret
```
From my understanding, the fp16 custom variable getter's function is to convert all variables that are originally FP32 to FP16. But the code above seems to convert variables that are originally FP16 to FP16 (and changing the dtype to float32). So it makes more sense to me to:
```
if kwargs['dtype'] == tf.float32:
   kwargs['dtype'] = tf.float16
....
```
I'm not familiar with Tensorflow's custom_getter implementation so I'd appreciate your thoughts on this. Thanks very much!

**Comment by ppwwyyxx** [comment]
Please refer to https://docs.nvidia.com/deeplearning/sdk/mixed-precision-training/index.html
