### ISSUE TITLE
Request of feature denoising resnet-152 checkpoint trained on clean images.

### ISSUE THREAD

**Issue by MaureenZOU** [facebookresearch/ImageNet-Adversarial-Training#19]
I have played with your feature denoising module trained with adversarial images. And I am wondering whether it is possible to release the model on Table.3 (https://arxiv.org/pdf/1812.03411.pdf). Thanks a lot!

**Comment by ppwwyyxx** [comment]
We have no such plans. Since training on clean images is much cheaper, you can train them yourself with `--attack-iter 0`.
