### ISSUE TITLE
Black-box attack code

### ISSUE THREAD

**Issue by Cold-Winter** [facebookresearch/ImageNet-Adversarial-Training#5]
Can you please release black-box attack code?

**Comment by Cold-Winter** [comment]
Can you please release black-box attack code?

**Comment by ppwwyyxx** [comment]
I'm not sure what code you're asking for. Our paper does not do black-box attack.

**Comment by ppwwyyxx** [comment]
If you're referring to the CAAD 2018 black-box attacks that we evaluate our models on: these attacks are from other competitors and have not been made public by them.

If you're referring to the CAAD 2017 top-5 black-box attacks that we evaluate our models on: they are made public by their original authors. We can provide you the links to them if you need.

**Comment by Cold-Winter** [comment]
Ok. I can find them. Thanks very much.

**Comment by XingangPan** [comment]
@ppwwyyxx For the CAAD 2017 top-5 black-box attacks, I can only find the code of team 'iwiwi' and 'toshi_k'. I would appreciate if you could provide the links to the other three teams 'TSAIL', 'Sangxia', and 'Stanford & Sun'. Thanks.

**Comment by cihangxie** [comment]
TSAIL: https://github.com/dongyp13/Non-Targeted-Adversarial-Attacks
Sangxia: https://github.com/sangxia/nips-2017-adversarial
Stanford & Sun: https://github.com/ftramer/stanford-suns-nips17
