### ISSUE TITLE
Plan to release ResNet101  baseline model?

### ISSUE THREAD

**Issue by wjyouch** [facebookresearch/ImageNet-Adversarial-Training#6]
Hello,

I am wondering could you release the baseline ResNet101/50 models? This will help analyze the model robustness of different architectures.Thank you.

**Comment by ppwwyyxx** [comment]
Thanks for your interest in our models! Our main results are reported on ResNet-152, so we've only released ResNet-152 models. Fow now we don't have plan to release the smaller models.
