### ISSUE TITLE
Running without horovod? 

### ISSUE THREAD

**Issue by lhfowl** [facebookresearch/ImageNet-Adversarial-Training#8]
I'm having trouble getting horovod installed properly on my computer. Is there away to predict on the model without horovod?

**Comment by ppwwyyxx** [comment]
You can use [inference-example.py](https://github.com/facebookresearch/ImageNet-Adversarial-Training/blob/master/inference-example.py).

You can also remove everything in main.py about horovod and use the `hvd.size() == 1` codepath only: https://github.com/facebookresearch/ImageNet-Adversarial-Training/blob/c704ef76467225aba0a69b3c5d04333b7f3f9526/main.py#L201-L204
