### ISSUE TITLE
How do you visualize features in the paper

### ISSUE THREAD

**Issue by krumo** [facebookresearch/ImageNet-Adversarial-Training#9]
Hi, thanks for your impressive work! I wonder how do you visualize the features before and after denoising as in the paper. Sorry I unable to find any details about the visualization methods in the paper. Plus, do you have any plan for releasing your code for visualization? Thanks in advance!

**Comment by ppwwyyxx** [comment]
Thanks for your interest.
We visualize the features by: (1) compute the features of shape CxHxW; (2) pick a channel; (3) draw the HxW image. There is nothing special about the process. We have no plan to release code for this.

**Comment by krumo** [comment]
@ppwwyyxx I see. Thanks for your detailed explanation!

**Comment by say2sarwar** [comment]
Which layer did you used for visualization? the images in the paper and it's feature map are from which layer? Thanks in advance.

**Comment by ppwwyyxx** [comment]
It's from a res3 block as mentioned in the paper.

**Comment by say2sarwar** [comment]
thank you so much.
